### ISSUE TITLE
Docker image isn't updating.

### ISSUE THREAD

**Issue by Katorone** [vinanrra/Docker-Satisfactory#12]
$ docker pull vinanrra/satisfactory-server
`latest: Pulling from vinanrra/satisfactory-server
Digest: sha256:af544d01e1c7d2754316cedfe7d9750bb1930ff5fa436472940a2919c7dc6c25
Status: Image is up to date for vinanrra/satisfactory-server:latest
docker.io/vinanrra/satisfactory-server:latest`

$ docker inspect -f '{{ index .Config.Labels "build_version" }}' vinanrra/satisfactory-server
`version: 0.0.1`

Shouldn't this be version 0.0.5 ?

**Comment by vinanrra** [comment]
My bad, will update manually, but going to add something to change automatically
