### ISSUE TITLE
How to force container to autorestart when sffactory fails?

### ISSUE THREAD

**Issue by damccull** [vinanrra/Docker-Satisfactory#18]
I understand the container should monitor for crashing server and restart it. I'm running this in docker stack and trying to reload the container with `docker service update --force satisfactory_service`. It does force a container rebuild but the second container seems to have some kind of steam issue that doesn't allow sfserver to start. Then the container just sits there dead until I restart it again or remove and recreate the stack.

Is there a way to fix the monitor so that it picks up on this issue, or at least a way to force the container to restart entirely if sfserver doesn't start?

**Comment by vinanrra** [comment]
If you have `MONITOR=YES` that should do it, if it's not working I need more information and logs to debug the problem.
