### ISSUE TITLE
Experimental Version Setting

### ISSUE THREAD

**Issue by VectorXYZing** [vinanrra/Docker-Satisfactory#19]
This is great work and I can get it working perfectly for the current public version of the server. I cannot work out how to set it to use the experimental version of the sever?

Any guidance greatly appreciated. I know it will be simple but nothing I have tried has worked!

**Comment by vinanrra** [comment]
I will check it ASAP, but i'm on vacations

**Comment by vinanrra** [comment]
You should change:

VERSION=public

To desired version:

![image](https://user-images.githubusercontent.com/4247187/187024438-32bfbfc1-7790-4418-80bb-3667f53795c8.png)
