### ISSUE TITLE
How to download save file from docker server

### ISSUE THREAD

**Issue by Hademma** [vinanrra/Docker-Satisfactory#21]
I have tried to find the save file for the savegame in my server, but it is unreacheble. I have tried putty, filzilla, WINscp and the consol in portainer and the only place i find the savegame is in portainer consol but can not copy og move it from folder to anoter folder on local og to my desktop over LAN. Pleeas help

**Comment by vinanrra** [comment]
Hi,

It should be here:

`/home/sfserver/.config/Epic/FactoryGame/Saved/SaveGames` inside the container, so you need look at your docker-compose or the docker command that you have used to know where it's the folder at your host system.

Greetings
