### ISSUE TITLE
Starting server error.

### ISSUE THREAD

**Issue by Skysec0230** [vinanrra/Docker-Satisfactory#22]
Having an issue with starting server, install went fine except im having an error with dependencies missing. Specifically, distro-info. 
Starting sfserver: Missing dependencies [WARN] Starting sfserver: Missing dependencies: distro-info sudo dpkg --add-architecture i386; sudo apt update; sudo apt install distro-info. When trying these commands in ssh via putty, i get errors. "sudo dpkg --add-architecture i386" just moves to the next line seemingly doing nothing at all. "sudo apt update" gives me error apt: command not found and the same for the last command. Any ideas? Ive done the PUID and PGID but maybe thats the issue, your PGID is defaulted to 1000, where as mine is 100. So not sure where that might have gone wrong?

**Comment by Skysec0230** [comment]
"Warning! Missing dependencies: distro-info                                                                                                  
Warning! sfserver does not have sudo access. Manually install dependencies.                                                                 
sudo dpkg --add-architecture i386; sudo apt update; sudo apt install distro-info"

**Comment by Skysec0230** [comment]
now getting error "]LogSteamShared: Warning: Steam Dedicated Server API failed to initialize."

**Comment by Skysec0230** [comment]
update: first start goes well except i cannot connect. I get pings to the server but game shows server as offline. after restarting server i get massive errors. 

"[2023.04.07-03.43.31:947][  0]LogStreaming: Error:   /Game/FactoryGame/Prototype/WAT/Desc_WAT1                                              
[2023.04.07-03.43.31:948][  0]LogStreaming: Error: Couldn't find file for package /Game/FactoryGame/Schematics/Story/Schematic_ObjectScanner
_WAT2 requested by async loading code. NameToLoad: /Game/FactoryGame/Schematics/Story/Schematic_ObjectScanner_WAT2                          
[2023.04.07-03.43.31:948][  0]LogStreaming: Error: Found 1 dependent packages...                                                            
[2023.04.07-03.43.31:948][  0]LogStreaming: Error:   /Game/FactoryGame/Prototype/WAT/Desc_WAT2  "


"[2023.04.07-03.43.33:089][  0]LogGenericPlatformMisc: Error: SetEnvironmentVar not implemented for this platform: SteamAppId = 526870       
dlopen failed trying to load:                                                                                                               
steamclient.so                                                                                                                              
with error:                                                                                                                                 
steamclient.so: cannot open shared object file: No such file or directory                                                                   
[S_API] SteamAPI_Init(): Loaded '/home/sfserver/.steam/sdk64/steamclient.so' OK.  (First tried local 'steamclient.so') "

^ this last error repeats 3 times.

The container stays running, however i cannot connect and get this when i ping the server "2023.04.07-03.46.41:669][646]LogNet: NotifyAcceptingConnection accepted from: XXX.XX.X.X:XXXXX"
Where the x's are the IP.

**Comment by vinanrra** [comment]
Hi, those issues are fixed now, sorry for the delay :(
