### ISSUE TITLE
Savegame Volume missing in docker-compose.yaml

### ISSUE THREAD

**Issue by TheClockTwister** [vinanrra/Docker-Satisfactory#26]
You did not specify the volume mount in your docker-compose.yaml.

It's a great image and works right out-of-the-box, but upon restart i was greeted with a fresh map
and had to locate the savegame files myself and mount tmen.

Would be cool if you added it in the docker-compose.yaml to prevent this...

:)
Best regards

**Comment by TheClockTwister** [comment]
I just noticed, you actually have it in the docker-compose.yaml on GitHub. But the README on DockerHub does **not** have it in the compose section!

Easy fix ;)

**Comment by vinanrra** [comment]
Thanks for the feedback, I'm on vacations these days I will change it later.

**Comment by TheClockTwister** [comment]
Have a nice vacation then! :)
I'll leave the issue open as a reminder...
Just close it when you update the README on DockerHub.

**Comment by TheClockTwister** [comment]
thanks! Have fun with the v1.0  ^^
