### ISSUE TITLE
Server update to version 1.0.0.3

### ISSUE THREAD

**Issue by otomotho** [vinanrra/Docker-Satisfactory#31]
Hello,

It is possible to update the image in version 1.0.0.3 ? 
Actually is in version 1.0.0.2
![Capture d'écran 2024-09-25 180433](https://github.com/user-attachments/assets/25002e50-2eef-41ca-be77-3d9fdc634bb4)

thanks mate :)

**Comment by delta-whiplash** [comment]
Hello I have the same issue 
@vinanrra do you have a fix

**Comment by vinanrra** [comment]
You need to update the server, the docker image isn't linked to any version

https://github.com/vinanrra/Docker-Satisfactory?tab=readme-ov-file#start-modes
