### ISSUE TITLE
Frquent crashes after the 1.0.0.6 update

### ISSUE THREAD

**Issue by tonyhudoletnjak** [vinanrra/Docker-Satisfactory#34]
I updated server from 1.0.0.4 to 1.0.0.6 and image v0.1.1 to v0.1.2 and now my server crashes all the time. 

There is no useful information in the log. Container just stops being responsive and all of the resource usage goes to minimum.

**Comment by tonyhudoletnjak** [comment]
Server log: 
[sfserver-console.log](https://github.com/user-attachments/files/17708219/sfserver-console.log)
Client log: 
[FactoryGame.log](https://github.com/user-attachments/files/17708220/FactoryGame.log)
To me it's not really clear what is the issue. 

TBH I do not think this is a problem with the image but I do not know how to rollback to previous version of the game server.

**Comment by vinanrra** [comment]
If the server it's loading up and crash, it seems to be an issue with the game or the host machine
