### ISSUE TITLE
Wierd lag

### ISSUE THREAD

**Issue by Mega-Bits** [vinanrra/Docker-Satisfactory#5]
Just found this container/docker build today and tried it out. Everything seems to work fine, but on the server a noticed a wierd lag. I noticed it at first when building and extremly clear when entering a hyper tube. There is a delay like 0,5-1,0 second when entering a hyper tube and with building too.

So i tried my old method (Ubuntu 20.04. container with just the game in it, not even steamcmd installed) and there was not this issue. So i dont know if this is importend but in my Ubuntu container the, the complete server, execpt the savegames, are located on the host machine.

I hope i could explaine this correct.

Using docker compose(stack) with these settings in portainer:
```docker
version: '2'
services:
  sfserver:
    image: vinanrra/satisfactory-server
    container_name: sfserver
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    #entrypoint: /bin/bash For testing on my end
    environment:
      - START_MODE=1 # Change between START MODES
      - PUID=10004 # Remember to use same as your user
      - PGID=10004 # Remember to use same as your user
      - TimeZone=Europe/Berlin
      - TEST_ALERT=NO
      - BACKUP=YES # Backup server at 5 AM
      - MONITOR=YES # Keeps server up if crash
      - VERSION=public # Change between server versions
    volumes:
      - /opt/docker/satisfactory/ServerFiles:/home/sfserver/serverfiles/ # Optional, serverfiles
      - /opt/docker/satisfactory/log:/home/sfserver/log/ # Optional, logs
      - /opt/docker/satisfactory/backups:/home/sfserver/lgsm/backup/ # Optional, backups
      - /opt/docker/satisfactory/LGSM-Config:/home/sfserver/lgsm/config-lgsm/sfserver # Optional, LGSM-Config
      - /opt/docker/satisfactory/SavesGames:/home/sfserver/.config/Epic/FactoryGame/Saved/SaveGames # Satisfactory Saves
    ports:
      - 15777:15777/udp
      - 15000:15000/udp
      - 7777:7777/udp
    restart: unless-stopped #NEVER USE WITH START_MODE=4 or START_MODE=0
```

Best regards me

**Comment by vinanrra** [comment]
Hi, thanks for the info, I will try to reproduce, because I'm not having any issues, could you send me your save? @Mega-Bits

**Comment by Mega-Bits** [comment]
> 
> 
> Hi, thanks for the info, I will try to reproduce, because I'm not having any issues, could you send me your save? @Mega-Bits

I think i found the cultrip and it happens on both "servers" so sorry for false blame.

It is this error i think:
```
[2021.11.05-17.41.14:781][137]LogNet: UNetDriver::TickDispatch: Very long time between ticks. DeltaTime: 6.07, Realtime: 6.08. IpNetDriver_2147465470
[2021.11.05-17.41.14:781][137]LogNet: UNetDriver::TickDispatch: Very long time between ticks. DeltaTime: 6.07, Realtime: 6.08. EOSNetDriver_2147482351
```

but who knows

**Comment by vinanrra** [comment]
> > 
> > 
> > Hi, thanks for the info, I will try to reproduce, because I'm not having any issues, could you send me your save? @Mega-Bits
> 
> I think i found the cultrip and it happens on both "servers" so sorry for false blame.
> 
> It is this error i think:
> ```
> [2021.11.05-17.41.14:781][137]LogNet: UNetDriver::TickDispatch: Very long time between ticks. DeltaTime: 6.07, Realtime: 6.08. IpNetDriver_2147465470
> [2021.11.05-17.41.14:781][137]LogNet: UNetDriver::TickDispatch: Very long time between ticks. DeltaTime: 6.07, Realtime: 6.08. EOSNetDriver_2147482351
> ```
> 
> but who knows 

It's okay, I'm gonna close the ticket then :)
