### ISSUE TITLE
./sfserver update : Permission denied

### ISSUE THREAD

**Issue by Ethoytaryn** [vinanrra/Docker-Satisfactory#9]
Hello,

I have an error when I try to use the command ./sfserver update

![image](https://user-images.githubusercontent.com/17123597/144108339-b5a67604-a355-48d5-8536-5f56b78b8224.png)

I use docker-compose to run container. I expected an user error but PUID and PGID are the same on host and container.

do you have any idea where the problem would come from ?

Best regards

Guillaume

**Comment by vinanrra** [comment]
Gonna check, but did you try updating the server with the start mode 2 or 3?

**Comment by vinanrra** [comment]
Just check without the su-exec and works too, don't know why your isn't working

![imagen](https://user-images.githubusercontent.com/4247187/144132330-1607f8d8-8c79-43ed-ac16-21c89fe47963.png)

**Comment by vinanrra** [comment]
Now i had same error, gonna check it

**Comment by vinanrra** [comment]
Start mode work properly:

![imagen](https://user-images.githubusercontent.com/4247187/144142372-8a8a1a61-2ac3-4b89-b5cd-4d046ba113f7.png)

**Comment by vinanrra** [comment]
I found the issue:

![imagen](https://user-images.githubusercontent.com/4247187/144142476-0d1318a0-4ceb-4711-900b-c4376860ba44.png)

**Comment by Ethoytaryn** [comment]
Thux u so much, now it's work =)
